# Our curriculum structure

| Lesson Program | Lesson | Episode | 
| -------------- | ------ | ------- | 
| Data Carpentry | Data Organization in Spreadsheets for Ecologists | Exporting data |
| | Data Wrangling and Processing for Genomics | Assessing Read Quality |
| Library Carpentry | Open Refine | Faceting and filtering | 
| | The Unix Shell | Automating the tedious with loops |
| Software Carpentry | Plotting and Programming in Python | Writing Functions |
| | R para Análisis Científicos Reproducibles | Guardando datos | 
Data Carpentry lessons are domain-specific, and lessons that are taught together form a "curriculum". 

## Episodes

An episode is a single block of content and renders as a single page of a lesson website.
Each episode teaches a set of related concepts (for example, 
[navigating files and directories](http://swcarpentry.github.io/shell-novice/02-filedir/index.html) 
or [indexing and subsetting data](https://datacarpentry.org/python-ecology-lesson/03-index-slice-subset/index.html)). 
It lists measurable learning objectives related to those concepts
and contains a number of challenges to assess
learners' ability to perform those learning objectives. Episodes within a lesson can be
dependent on earlier episodes and are generally taught in sequence. 

## Lessons

A lesson is a collection of episodes that together help the learner to develop a particular
set of competencies 
(for example, [version control](http://swcarpentry.github.io/git-novice/) or 
[data organization](http://www.datacarpentry.org/spreadsheets-socialsci/)). 
Each lesson has a landing page that lists all its episodes as well
as the overall learning objectives. The overall learning objectives for the lesson
should be met by its episodes. Assessment of lesson-level learning outcomes is summative and
can be addressed with a post-workshop survey. Lessons can be used independently and should
not rely on concepts from other lessons. Lessons may have optional episodes, but lesson
designers should provide a recommended structure or structures for what episodes should
be taught together and in what order.

## Curricula

A curriculum is a set of lessons that together teach skills needed in a particular
domain (for example, [genomics](https://datacarpentry.org/genomics-workshop/) or 
[geospatial research](https://datacarpentry.org/geospatial-workshop/)). A curriculum has a
landing page listing its component lessons and overall learning objectives, and describing
the data used in the curriculum. Carpentries curricula often have a narrative structure,
where lessons are explicitly linked in a sequence, for example, as steps in a data handling
workflow.

## Lesson Collections

A lesson collection is the full set of lessons housed within
a specific Lesson Program (for example, all [Software Carpentry lessons](https://software-carpentry.org/lessons/)), or
within The Carpentries organization (including our [Instructor Training](https://carpentries.github.io/instructor-training/) and 
[Trainer Training](https://carpentries.github.io/trainer-training/) lessons).
Lessons within a collection should match the target audience of the Lesson Program or
the broader Carpentries community. 
