# (APPENDIX) Appendix {-}

# The Lesson Proposal

## For all lessons

1. **A short description** -- It should be less than 200 characters and capture
   the type of data and general audience for the lesson (e.g., "Tabular Data for
   Phylogeneticsts", or "Data Managemnet for Digital Humanities".)
2. **The intended audience** -- Who is the target audience for this lesson?
   (e.g. Graduate-level researchers in ecology).
3. **Duration of the lesson** -- How long is this lesson? 1.5, 3, 6, or 12
   hours.
4. **Fit with existing Carpentries lesson** -- Could this lesson be added or be
   swapped with an existing lesson in our existing curriculum (e.g., a proposed
   lesson on Rmarkdown, using the Ecology dataset, could replace the episode on
   interacting with databases).
5. **Tools used** -- Describe the software, packages, libraries that will be
    taught in the lesson. Make it clear if any of them are not open source
    licensed (i.e., they are not listed on the [Open Source Initiative website](https://opensource.org/licenses)).
6. **Suggestions for the dataset to use** -- review our [dataset recommendations][Picking a dataset] and describe the datasets you would like
   to use if it's not one that is already in use in our lessons.
7. **A brief lesson outline** -- For each half day of material, please describe:
   * 3–6 concrete learning objectives.
   * An end-of-lesson assessment exercise to demonstrate the skills participants
    have learned.
   * A summary of the tools and data set(s) that will be used.
   * A point-form learning plan
   * A brief comparison with existing open-access lessons on the subject.
8. **Evidence of need** -- Summarize evidence that researchers need this lesson.
     This summary may include links to online discussions (mailing lists,
     twitter, etc) or publications (e.g., descriptions of practices that are not
     yet widely adopted), results of surveys, etc.
9. **Development Team** -- Who are the people involved? Are they certified
    Carpentries instructors? What is their experience developing teaching
    materials in general and for the Carpentries in particular?
10. **Development Plan and Timeline** -- The development plan must include a
    timeline that makes specific people responsible for specific lesson modules,
    commitments from specific sites to teach trial versions of the lesson, a
    date and location for a hackathon (if appropriate), etc. We recognize that
    this plan may change as lesson development progress, but the more specific
    it is, the more credible the proposal will be.
11. **Support** -- Explain who will support lesson development and how. If you
    have secured funding, attach details. If you have not, but intend to seek
    it, describe any planned or submitted funding requests. If the work is not
    being funded, explain how development and delivery will be supported.


## For Grant-Supported lessons


## Transition to officially supported lesson

